### ISSUE TITLE
프로젝트 Milestone 작성

### ISSUE THREAD

**Issue by insightp25** [insightp25/ticketing-server-design#1]
### Milestone 설정 대상 항목
- [ ] 시나리오 요구사항 분석
- [ ] ERD 설계
- [ ] API 명세 및 Mock API 작성
- [ ] API 문서 작성
- [ ] 비즈니스 로직 개발
- [ ] 단위테스트
- [ ] 유저 시나리오에 따른 통합테스트 등
